[package]
name = "valuable-derive"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>", "Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Values"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.60", features = ["extra-traits"] }

[dev-dependencies]
valuable = { path = "../valuable", features = ["derive"] }
