name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - run: cargo test --all-features --workspace
      - run: cargo build --all-features --all-targets --workspace

  no-std:
    strategy:
      fail-fast: false
      matrix:
        # thumbv7m-none-eabi supports atomic CAS.
        # thumbv6m-none-eabi supports atomic, but not atomic CAS.
        # riscv32i-unknown-none-elf does not support atomic at all.
        target:
          - thumbv6m-none-eabi
          - thumbv7m-none-eabi
          - riscv32i-unknown-none-elf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - run: rustup target add ${{ matrix.target }}
      - run: cargo hack build --target ${{ matrix.target }} --feature-powerset --skip std,default
        working-directory: valuable
      - run: cargo hack build --target ${{ matrix.target }} --feature-powerset --skip std,default
        working-directory: valuable-serde

  features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - run: cargo hack build --workspace --feature-powerset

  # When this job failed, run ci/no_atomic.sh and commit result changes.
  # TODO(taiki-e): Ideally, this should be automated using a bot that creates
  #                PR when failed, but there is no bandwidth to implement it
  #                right now...
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - run: ci/no_atomic.sh
      - run: git diff --exit-code

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - run: cargo fmt --all -- --check

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -Dwarnings
